/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_monsgamemodel_free(a: number): void;
export function monsgamemodel_from_fen(a: number, b: number): number;
export function monsgamemodel_fen(a: number, b: number): void;
export function monsgamemodel_process_input(a: number, b: number, c: number, d: number): number;
export function monsgamemodel_process_input_fen(a: number, b: number, c: number): number;
export function monsgamemodel_item(a: number, b: number): number;
export function monsgamemodel_square(a: number, b: number): number;
export function monsgamemodel_is_later_than(a: number, b: number, c: number): number;
export function monsgamemodel_active_color(a: number): number;
export function monsgamemodel_winner_color(a: number): number;
export function monsgamemodel_black_score(a: number): number;
export function monsgamemodel_white_score(a: number): number;
export function monsgamemodel_available_move_kinds(a: number, b: number): void;
export function monsgamemodel_locations_with_content(a: number, b: number): void;
export function __wbg_outputmodel_free(a: number): void;
export function __wbg_get_outputmodel_kind(a: number): number;
export function __wbg_set_outputmodel_kind(a: number, b: number): void;
export function outputmodel_locations(a: number, b: number): void;
export function outputmodel_next_inputs(a: number, b: number): void;
export function outputmodel_events(a: number, b: number): void;
export function outputmodel_input_fen(a: number, b: number): void;
export function __wbg_itemmodel_free(a: number): void;
export function __wbg_manamodel_free(a: number): void;
export function __wbg_get_manamodel_kind(a: number): number;
export function __wbg_set_manamodel_kind(a: number, b: number): void;
export function __wbg_get_manamodel_color(a: number): number;
export function __wbg_set_manamodel_color(a: number, b: number): void;
export function __wbg_nextinputmodel_free(a: number): void;
export function __wbg_get_nextinputmodel_location(a: number): number;
export function __wbg_set_nextinputmodel_location(a: number, b: number): void;
export function __wbg_get_nextinputmodel_modifier(a: number): number;
export function __wbg_set_nextinputmodel_modifier(a: number, b: number): void;
export function __wbg_get_nextinputmodel_kind(a: number): number;
export function __wbg_set_nextinputmodel_kind(a: number, b: number): void;
export function __wbg_get_nextinputmodel_actor_mon_item(a: number): number;
export function __wbg_set_nextinputmodel_actor_mon_item(a: number, b: number): void;
export function __wbg_eventmodel_free(a: number): void;
export function __wbg_squaremodel_free(a: number): void;
export function __wbg_mon_free(a: number): void;
export function __wbg_get_mon_kind(a: number): number;
export function __wbg_set_mon_kind(a: number, b: number): void;
export function __wbg_get_mon_color(a: number): number;
export function __wbg_set_mon_color(a: number, b: number): void;
export function __wbg_get_mon_cooldown(a: number): number;
export function __wbg_set_mon_cooldown(a: number, b: number): void;
export function mon_new(a: number, b: number, c: number): number;
export function mon_is_fainted(a: number): number;
export function mon_faint(a: number): void;
export function mon_decrease_cooldown(a: number): void;
export function __wbg_location_free(a: number): void;
export function __wbg_get_location_i(a: number): number;
export function __wbg_set_location_i(a: number, b: number): void;
export function __wbg_get_location_j(a: number): number;
export function __wbg_set_location_j(a: number, b: number): void;
export function location_new(a: number, b: number): number;
export function winner(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number): void;
export function __wbindgen_malloc(a: number, b: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number, d: number): number;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_free(a: number, b: number, c: number): void;
