/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_mon_free(a: number): void;
export function __wbg_get_mon_kind(a: number): number;
export function __wbg_set_mon_kind(a: number, b: number): void;
export function __wbg_get_mon_color(a: number): number;
export function __wbg_set_mon_color(a: number, b: number): void;
export function __wbg_get_mon_cooldown(a: number): number;
export function __wbg_set_mon_cooldown(a: number, b: number): void;
export function mon_new(a: number, b: number, c: number): number;
export function mon_is_fainted(a: number): number;
export function mon_faint(a: number): void;
export function mon_decrease_cooldown(a: number): void;
export function __wbg_location_free(a: number): void;
export function __wbg_get_location_i(a: number): number;
export function __wbg_set_location_i(a: number, b: number): void;
export function __wbg_get_location_j(a: number): number;
export function __wbg_set_location_j(a: number, b: number): void;
export function location_new(a: number, b: number): number;
export function __wbg_monsgamemodel_free(a: number): void;
export function monsgamemodel_from_fen(a: number, b: number): number;
export function monsgamemodel_fen(a: number, b: number): void;
export function monsgamemodel_active_color(a: number): number;
export function monsgamemodel_winner_color(a: number): number;
export function monsgamemodel_black_score(a: number): number;
export function monsgamemodel_white_score(a: number): number;
export function monsgamemodel_available_move_kinds(a: number, b: number): void;
export function winner(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number): void;
export function __wbindgen_malloc(a: number, b: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number, d: number): number;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_free(a: number, b: number, c: number): void;
